import sys
sys.dont_write_bytecode = True

DELAYED_EXECUTION = True
PRINT_PNL = False
PRINT_TRADES = True
PLOT_PERFORMANCE = False
STREAM_HISTORY_LEN = 50
PRINT_OPTIMIZATION_RUN = False
CALC_ROLLING_STATS = False
INITIAL_CASH = 100000
LOG_TRADES_TO_FILE = False
